import {
  Child,
  AttendanceRecord,
  DaycareProviderProfile,
  DailyReport,
  SafetyTask,
  IncidentRecord,
  MediaItem,
  AuditLogEntry,
  CalendarEvent,
  PhotoItem,
} from './types';

export const INITIAL_CHILDREN: Child[] = [
  {
    id: 'child-1',
    firstName: 'Emma',
    lastName: 'Watson',
    preferredName: 'Emma',
    dateOfBirth: '2023-04-12',
    ageYears: 3,
    ageMonths: 4,
    gender: 'Female',
    parentName: 'Sarah Watson',
    parentEmail: 'sarah.watson@example.com',
    parentPhone: '(555) 234-5678',
    emergencyContacts: [
      { name: 'David Watson (Father)', relation: 'Father', phone: '(555) 234-5679' },
      { name: 'Eleanor Vance (Grandmother)', relation: 'Grandmother', phone: '(555) 987-6543' },
    ],
    authorizedPickups: [
      { name: 'Sarah Watson', relation: 'Mother', phone: '(555) 234-5678' },
      { name: 'David Watson', relation: 'Father', phone: '(555) 234-5679' },
    ],
    enrollmentStatus: 'enrolled',
    dietaryRestrictions: ['No artificial dyes'],
    allergies: ['Peanuts (Severe - EpiPen on site)', 'Shellfish'],
    authorizedMedications: ['EpiPen Jr 0.15mg', 'Children Benadryl (with written consent)'],
    sleepPreferences: 'Prefers quiet corner with lavender plush bunny. Sleeps best on low cot.',
    comfortPreferences: 'Soft lullaby or storybook before resting. Loves tactile sensory books.',
    specialInstructions: 'Always verify EpiPen expiry on 1st of every month. Sunscreen SPF 50+ before outdoor play.',
    avatarUrl: 'https://images.unsplash.com/photo-1543332164-6e82f355badc?w=150&auto=format&fit=crop&q=80',
    isCheckedIn: true,
    checkInTime: '08:02 AM',
    timeline: [
      { id: 't1', time: '08:02 AM', title: 'Checked In', category: 'checkin', completed: true, notes: 'Arrived cheerful with mom Sarah. Shoes placed in cubby #4.' },
      { id: 't2', time: '09:15 AM', title: 'Breakfast', category: 'meal', completed: true, notes: 'Whole grain oatmeal with banana slices. 100% finished.' },
      { id: 't3', time: '10:00 AM', title: 'Outdoor Activity', category: 'activity', completed: true, notes: 'Sandbox exploration and tricycle relay with Lucas.' },
      { id: 't4', time: '11:20 AM', title: 'Snack', category: 'meal', completed: true, notes: 'Apple quarters and cheddar cubes.' },
      { id: 't5', time: '12:30 PM', title: 'Lunch', category: 'meal', completed: true, notes: 'Steamed turkey meatballs, broccoli florets, and water.' },
      { id: 't6', time: '01:05 PM', title: 'Nap Started', category: 'nap', completed: true, notes: 'Cot #3 with plush bunny. Fell asleep smoothly.' },
      { id: 't7', time: '02:30 PM', title: 'Nap Ended', category: 'nap', completed: true, notes: 'Woke naturally, diaper checked and fresh.' },
      { id: 't8', time: '03:15 PM', title: 'Art Activity', category: 'activity', completed: true, notes: 'Finger-painted autumn leaf tree collage.' },
      { id: 't9', time: '04:45 PM', title: 'Checked Out', category: 'checkout', completed: false, notes: 'Expected pickup by father David.' },
      { id: 't10', time: '06:00 PM', title: 'End', category: 'other', completed: false, notes: 'Daily daycare closing time.' },
    ],
  },
  {
    id: 'child-2',
    firstName: 'Liam',
    lastName: 'Johnson',
    preferredName: 'Liam',
    dateOfBirth: '2022-11-05',
    ageYears: 3,
    ageMonths: 9,
    gender: 'Male',
    parentName: 'Marcus Johnson',
    parentEmail: 'marcus.j@example.com',
    parentPhone: '(555) 345-6789',
    emergencyContacts: [
      { name: 'Angela Johnson', relation: 'Mother', phone: '(555) 345-6780' },
    ],
    authorizedPickups: [
      { name: 'Marcus Johnson', relation: 'Father', phone: '(555) 345-6789' },
      { name: 'Angela Johnson', relation: 'Mother', phone: '(555) 345-6780' },
    ],
    enrollmentStatus: 'enrolled',
    dietaryRestrictions: ['Lactose sensitive (Lactose-free milk provided)'],
    allergies: ['None reported'],
    authorizedMedications: [],
    sleepPreferences: 'Prefers cot near open window airflow.',
    comfortPreferences: 'Loves wooden train tracks.',
    specialInstructions: 'Potty training stage 2. Prompt every 90 minutes.',
    avatarUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=150&auto=format&fit=crop&q=80',
    isCheckedIn: true,
    checkInTime: '08:15 AM',
    timeline: [
      { id: 't1', time: '08:15 AM', title: 'Checked In', category: 'checkin', completed: true },
      { id: 't2', time: '09:15 AM', title: 'Breakfast', category: 'meal', completed: true },
      { id: 't3', time: '10:00 AM', title: 'Outdoor Activity', category: 'activity', completed: true },
      { id: 't4', time: '11:20 AM', title: 'Snack', category: 'meal', completed: true },
      { id: 't5', time: '12:30 PM', title: 'Lunch', category: 'meal', completed: true },
      { id: 't6', time: '01:05 PM', title: 'Nap Started', category: 'nap', completed: true },
      { id: 't7', time: '02:30 PM', title: 'Nap Ended', category: 'nap', completed: true },
      { id: 't8', time: '03:15 PM', title: 'Art Activity', category: 'activity', completed: true },
      { id: 't9', time: '04:45 PM', title: 'Checked Out', category: 'checkout', completed: false },
      { id: 't10', time: '06:00 PM', title: 'End', category: 'other', completed: false },
    ],
  },
  {
    id: 'child-3',
    firstName: 'Sophia',
    lastName: 'Martinez',
    preferredName: 'Sofi',
    dateOfBirth: '2024-02-18',
    ageYears: 2,
    ageMonths: 6,
    gender: 'Female',
    parentName: 'Elena Martinez',
    parentEmail: 'elena.m@example.com',
    parentPhone: '(555) 456-7890',
    emergencyContacts: [
      { name: 'Carlos Martinez', relation: 'Uncle', phone: '(555) 456-7899' },
    ],
    authorizedPickups: [
      { name: 'Elena Martinez', relation: 'Mother', phone: '(555) 456-7890' },
    ],
    enrollmentStatus: 'enrolled',
    dietaryRestrictions: ['Vegetarian'],
    allergies: ['Strawberries (Mild hives)'],
    authorizedMedications: [],
    sleepPreferences: 'Takes two shorter naps if needed.',
    comfortPreferences: 'Soft blanket and humming.',
    specialInstructions: 'Bilingual (Spanish & English). Responds well to both.',
    avatarUrl: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=150&auto=format&fit=crop&q=80',
    isCheckedIn: true,
    checkInTime: '08:20 AM',
    timeline: [
      { id: 't1', time: '08:20 AM', title: 'Checked In', category: 'checkin', completed: true },
      { id: 't2', time: '09:15 AM', title: 'Breakfast', category: 'meal', completed: true },
      { id: 't3', time: '10:00 AM', title: 'Outdoor Activity', category: 'activity', completed: true },
      { id: 't4', time: '11:20 AM', title: 'Snack', category: 'meal', completed: true },
      { id: 't5', time: '12:30 PM', title: 'Lunch', category: 'meal', completed: true },
      { id: 't6', time: '01:05 PM', title: 'Nap Started', category: 'nap', completed: true },
      { id: 't7', time: '02:30 PM', title: 'Nap Ended', category: 'nap', completed: true },
      { id: 't8', time: '03:15 PM', title: 'Art Activity', category: 'activity', completed: false },
      { id: 't9', time: '04:45 PM', title: 'Checked Out', category: 'checkout', completed: false },
      { id: 't10', time: '06:00 PM', title: 'End', category: 'other', completed: false },
    ],
  },
  {
    id: 'child-4',
    firstName: 'Noah',
    lastName: 'Brown',
    preferredName: 'Noah',
    dateOfBirth: '2022-09-14',
    ageYears: 3,
    ageMonths: 11,
    gender: 'Male',
    parentName: 'Chloe Brown',
    parentEmail: 'chloe.b@example.com',
    parentPhone: '(555) 567-8901',
    emergencyContacts: [
      { name: 'Arthur Brown', relation: 'Grandfather', phone: '(555) 567-8902' },
    ],
    authorizedPickups: [
      { name: 'Chloe Brown', relation: 'Mother', phone: '(555) 567-8901' },
    ],
    enrollmentStatus: 'enrolled',
    dietaryRestrictions: ['None'],
    allergies: ['None'],
    authorizedMedications: [],
    sleepPreferences: 'Deep sleeper.',
    comfortPreferences: 'Loves dinosaur building blocks.',
    specialInstructions: 'Needs extra pair of socks in cubby.',
    avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80',
    isCheckedIn: true,
    checkInTime: '08:30 AM',
    timeline: [
      { id: 't1', time: '08:30 AM', title: 'Checked In', category: 'checkin', completed: true },
      { id: 't2', time: '09:15 AM', title: 'Breakfast', category: 'meal', completed: true },
      { id: 't3', time: '10:00 AM', title: 'Outdoor Activity', category: 'activity', completed: true },
      { id: 't4', time: '11:20 AM', title: 'Snack', category: 'meal', completed: true },
      { id: 't5', time: '12:30 PM', title: 'Lunch', category: 'meal', completed: true },
      { id: 't6', time: '01:05 PM', title: 'Nap Started', category: 'nap', completed: true },
      { id: 't7', time: '02:30 PM', title: 'Nap Ended', category: 'nap', completed: true },
      { id: 't8', time: '03:15 PM', title: 'Art Activity', category: 'activity', completed: false },
      { id: 't9', time: '04:45 PM', title: 'Checked Out', category: 'checkout', completed: false },
      { id: 't10', time: '06:00 PM', title: 'End', category: 'other', completed: false },
    ],
  },
  {
    id: 'child-5',
    firstName: 'Olivia',
    lastName: 'Chen',
    preferredName: 'Livvy',
    dateOfBirth: '2023-08-30',
    ageYears: 3,
    ageMonths: 0,
    gender: 'Female',
    parentName: 'Mei Chen',
    parentEmail: 'mei.chen@example.com',
    parentPhone: '(555) 678-9012',
    emergencyContacts: [
      { name: 'Kevin Chen', relation: 'Father', phone: '(555) 678-9013' },
    ],
    authorizedPickups: [
      { name: 'Mei Chen', relation: 'Mother', phone: '(555) 678-9012' },
      { name: 'Kevin Chen', relation: 'Father', phone: '(555) 678-9013' },
    ],
    enrollmentStatus: 'enrolled',
    dietaryRestrictions: ['Nut-free facility policy'],
    allergies: ['Tree nuts'],
    authorizedMedications: [],
    sleepPreferences: 'Prefers reading 2 minutes before cot.',
    comfortPreferences: 'Singing songs.',
    specialInstructions: 'Loves water play.',
    avatarUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=150&auto=format&fit=crop&q=80',
    isCheckedIn: true,
    checkInTime: '08:35 AM',
    timeline: [
      { id: 't1', time: '08:35 AM', title: 'Checked In', category: 'checkin', completed: true },
      { id: 't2', time: '09:15 AM', title: 'Breakfast', category: 'meal', completed: true },
      { id: 't3', time: '10:00 AM', title: 'Outdoor Activity', category: 'activity', completed: true },
      { id: 't4', time: '11:20 AM', title: 'Snack', category: 'meal', completed: true },
      { id: 't5', time: '12:30 PM', title: 'Lunch', category: 'meal', completed: true },
      { id: 't6', time: '01:05 PM', title: 'Nap Started', category: 'nap', completed: true },
      { id: 't7', time: '02:30 PM', title: 'Nap Ended', category: 'nap', completed: true },
      { id: 't8', time: '03:15 PM', title: 'Art Activity', category: 'activity', completed: false },
      { id: 't9', time: '04:45 PM', title: 'Checked Out', category: 'checkout', completed: false },
      { id: 't10', time: '06:00 PM', title: 'End', category: 'other', completed: false },
    ],
  },
  {
    id: 'child-6',
    firstName: 'Lucas',
    lastName: 'Taylor',
    preferredName: 'Lucas',
    dateOfBirth: '2022-06-22',
    ageYears: 4,
    ageMonths: 2,
    gender: 'Male',
    parentName: 'Rachel Taylor',
    parentEmail: 'rachel.t@example.com',
    parentPhone: '(555) 789-0123',
    emergencyContacts: [
      { name: 'Sam Taylor', relation: 'Father', phone: '(555) 789-0124' },
    ],
    authorizedPickups: [
      { name: 'Rachel Taylor', relation: 'Mother', phone: '(555) 789-0123' },
    ],
    enrollmentStatus: 'enrolled',
    dietaryRestrictions: ['None'],
    allergies: ['None'],
    authorizedMedications: [],
    sleepPreferences: 'Quiet rest time 45 min.',
    comfortPreferences: 'Loves puzzle games.',
    specialInstructions: 'High energy, great leader in circle time.',
    avatarUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&auto=format&fit=crop&q=80',
    isCheckedIn: true,
    checkInTime: '08:40 AM',
    timeline: [
      { id: 't1', time: '08:40 AM', title: 'Checked In', category: 'checkin', completed: true },
      { id: 't2', time: '09:15 AM', title: 'Breakfast', category: 'meal', completed: true },
      { id: 't3', time: '10:00 AM', title: 'Outdoor Activity', category: 'activity', completed: true },
      { id: 't4', time: '11:20 AM', title: 'Snack', category: 'meal', completed: true },
      { id: 't5', time: '12:30 PM', title: 'Lunch', category: 'meal', completed: true },
      { id: 't6', time: '01:05 PM', title: 'Nap Started', category: 'nap', completed: true },
      { id: 't7', time: '02:30 PM', title: 'Nap Ended', category: 'nap', completed: true },
      { id: 't8', time: '03:15 PM', title: 'Art Activity', category: 'activity', completed: false },
      { id: 't9', time: '04:45 PM', title: 'Checked Out', category: 'checkout', completed: false },
      { id: 't10', time: '06:00 PM', title: 'End', category: 'other', completed: false },
    ],
  },
  {
    id: 'child-7',
    firstName: 'Mia',
    lastName: 'Gomez',
    preferredName: 'Mia',
    dateOfBirth: '2023-10-10',
    ageYears: 2,
    ageMonths: 10,
    gender: 'Female',
    parentName: 'Camila Gomez',
    parentEmail: 'camila.g@example.com',
    parentPhone: '(555) 890-1234',
    emergencyContacts: [
      { name: 'Diego Gomez', relation: 'Father', phone: '(555) 890-1235' },
    ],
    authorizedPickups: [
      { name: 'Camila Gomez', relation: 'Mother', phone: '(555) 890-1234' },
    ],
    enrollmentStatus: 'enrolled',
    dietaryRestrictions: ['Egg allergy'],
    allergies: ['Eggs'],
    authorizedMedications: [],
    sleepPreferences: 'Sleeps with lullaby.',
    comfortPreferences: 'Enjoys coloring.',
    specialInstructions: 'Verify snacks contain zero egg ingredients.',
    avatarUrl: 'https://images.unsplash.com/photo-1543332164-6e82f355badc?w=150&auto=format&fit=crop&q=80',
    isCheckedIn: true,
    checkInTime: '08:45 AM',
    timeline: [
      { id: 't1', time: '08:45 AM', title: 'Checked In', category: 'checkin', completed: true },
      { id: 't2', time: '09:15 AM', title: 'Breakfast', category: 'meal', completed: true },
      { id: 't3', time: '10:00 AM', title: 'Outdoor Activity', category: 'activity', completed: true },
      { id: 't4', time: '11:20 AM', title: 'Snack', category: 'meal', completed: true },
      { id: 't5', time: '12:30 PM', title: 'Lunch', category: 'meal', completed: true },
      { id: 't6', time: '01:05 PM', title: 'Nap Started', category: 'nap', completed: true },
      { id: 't7', time: '02:30 PM', title: 'Nap Ended', category: 'nap', completed: true },
      { id: 't8', time: '03:15 PM', title: 'Art Activity', category: 'activity', completed: false },
      { id: 't9', time: '04:45 PM', title: 'Checked Out', category: 'checkout', completed: false },
      { id: 't10', time: '06:00 PM', title: 'End', category: 'other', completed: false },
    ],
  },
  {
    id: 'child-8',
    firstName: 'Ethan',
    lastName: 'Wright',
    preferredName: 'Ethan',
    dateOfBirth: '2023-01-15',
    ageYears: 3,
    ageMonths: 7,
    gender: 'Male',
    parentName: 'Jessica Wright',
    parentEmail: 'jessica.w@example.com',
    parentPhone: '(555) 901-2345',
    emergencyContacts: [
      { name: 'Brian Wright', relation: 'Father', phone: '(555) 901-2346' },
    ],
    authorizedPickups: [
      { name: 'Jessica Wright', relation: 'Mother', phone: '(555) 901-2345' },
    ],
    enrollmentStatus: 'enrolled',
    dietaryRestrictions: ['Gluten-sensitive'],
    allergies: ['None'],
    authorizedMedications: [],
    sleepPreferences: 'Cot #8.',
    comfortPreferences: 'Story time.',
    specialInstructions: 'Brings own gluten-free crackers.',
    avatarUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=150&auto=format&fit=crop&q=80',
    isCheckedIn: true,
    checkInTime: '08:50 AM',
    timeline: [
      { id: 't1', time: '08:50 AM', title: 'Checked In', category: 'checkin', completed: true },
      { id: 't2', time: '09:15 AM', title: 'Breakfast', category: 'meal', completed: true },
      { id: 't3', time: '10:00 AM', title: 'Outdoor Activity', category: 'activity', completed: true },
      { id: 't4', time: '11:20 AM', title: 'Snack', category: 'meal', completed: true },
      { id: 't5', time: '12:30 PM', title: 'Lunch', category: 'meal', completed: true },
      { id: 't6', time: '01:05 PM', title: 'Nap Started', category: 'nap', completed: true },
      { id: 't7', time: '02:30 PM', title: 'Nap Ended', category: 'nap', completed: true },
      { id: 't8', time: '03:15 PM', title: 'Art Activity', category: 'activity', completed: false },
      { id: 't9', time: '04:45 PM', title: 'Checked Out', category: 'checkout', completed: false },
      { id: 't10', time: '06:00 PM', title: 'End', category: 'other', completed: false },
    ],
  },
  {
    id: 'child-9',
    firstName: 'Harper',
    lastName: 'Davis',
    preferredName: 'Harper',
    dateOfBirth: '2023-05-19',
    ageYears: 3,
    ageMonths: 3,
    gender: 'Female',
    parentName: 'Claire Davis',
    parentEmail: 'claire.d@example.com',
    parentPhone: '(555) 012-3456',
    emergencyContacts: [
      { name: 'Daniel Davis', relation: 'Father', phone: '(555) 012-3457' },
    ],
    authorizedPickups: [
      { name: 'Claire Davis', relation: 'Mother', phone: '(555) 012-3456' },
    ],
    enrollmentStatus: 'enrolled',
    dietaryRestrictions: ['None'],
    allergies: ['None'],
    authorizedMedications: [],
    sleepPreferences: 'Cot #9.',
    comfortPreferences: 'Doll accessory.',
    specialInstructions: 'Expected today at 09:30 AM (late drop-off doctor visit).',
    avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=150&auto=format&fit=crop&q=80',
    isCheckedIn: false,
    timeline: [
      { id: 't1', time: '09:30 AM', title: 'Checked In', category: 'checkin', completed: false, notes: 'Doctor checkup in morning' },
    ],
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  { id: 'att-1', childId: 'child-1', childName: 'Emma Watson', date: '2026-09-04', checkInTime: '08:02 AM', authorizedAdult: 'Sarah Watson (Mother)', providerName: 'Clara Oswald', verificationMethod: 'Biometric Face ID', notes: 'Arrived smiling and healthy', status: 'present' },
  { id: 'att-2', childId: 'child-2', childName: 'Liam Johnson', date: '2026-09-04', checkInTime: '08:15 AM', authorizedAdult: 'Marcus Johnson (Father)', providerName: 'Clara Oswald', verificationMethod: 'QR Code', notes: 'Lactose-free milk bag handed over', status: 'present' },
  { id: 'att-3', childId: 'child-3', childName: 'Sophia Martinez', date: '2026-09-04', checkInTime: '08:20 AM', authorizedAdult: 'Elena Martinez (Mother)', providerName: 'Clara Oswald', verificationMethod: 'QR Code', notes: 'Sun hat in cubby', status: 'present' },
  { id: 'att-4', childId: 'child-4', childName: 'Noah Brown', date: '2026-09-04', checkInTime: '08:30 AM', authorizedAdult: 'Chloe Brown (Mother)', providerName: 'Clara Oswald', verificationMethod: 'Staff PIN', notes: 'Extra clothes in bag', status: 'present' },
  { id: 'att-5', childId: 'child-5', childName: 'Olivia Chen', date: '2026-09-04', checkInTime: '08:35 AM', authorizedAdult: 'Mei Chen (Mother)', providerName: 'Clara Oswald', verificationMethod: 'Biometric Face ID', notes: 'Water bottle filled', status: 'present' },
  { id: 'att-6', childId: 'child-6', childName: 'Lucas Taylor', date: '2026-09-04', checkInTime: '08:40 AM', authorizedAdult: 'Rachel Taylor (Mother)', providerName: 'Clara Oswald', verificationMethod: 'QR Code', notes: 'Finished breakfast at home', status: 'present' },
  { id: 'att-7', childId: 'child-7', childName: 'Mia Gomez', date: '2026-09-04', checkInTime: '08:45 AM', authorizedAdult: 'Camila Gomez (Mother)', providerName: 'Clara Oswald', verificationMethod: 'Staff PIN', notes: 'Egg allergy protocol active', status: 'present' },
  { id: 'att-8', childId: 'child-8', childName: 'Ethan Wright', date: '2026-09-04', checkInTime: '08:50 AM', authorizedAdult: 'Jessica Wright (Mother)', providerName: 'Clara Oswald', verificationMethod: 'QR Code', notes: 'Gluten-free snacks packed', status: 'present' },
  { id: 'att-9', childId: 'child-9', childName: 'Harper Davis', date: '2026-09-04', checkInTime: '--', authorizedAdult: 'Claire Davis (Mother)', providerName: 'Clara Oswald', verificationMethod: 'Staff PIN', notes: 'Late arrival expected at 9:30 AM', status: 'expected' },
];

export const INITIAL_PROVIDERS: DaycareProviderProfile[] = [
  {
    id: 'prov-1',
    name: 'Little Stars Home Daycare',
    rating: 4.9,
    reviewCount: 28,
    distanceKm: 1.8,
    address: '142 Maplewood Avenue',
    city: 'Toronto',
    region: 'Ontario, Canada',
    isAccepting: true,
    minAgeMonths: 6,
    maxAgeYears: 5,
    hours: '7:30 AM – 5:30 PM',
    hourlyRate: 16.5,
    monthlyRate: 1250,
    licensedStatus: 'Licensed Home Child Care',
    mealsIncluded: true,
    outdoorPlay: true,
    petFree: true,
    languages: ['English', 'French'],
    capacityTotal: 10,
    capacityCurrent: 8,
    tagline: 'Safe • Caring • Play-Based Montessori Home Child Care',
    about: 'Warm, licensed home daycare specializing in early childhood development, organic culinary meals, spacious fenced outdoor sensory garden, and real-time computer vision safety protocols.',
    facilities: ['Fenced Outdoor Play Yard', 'Indoor Gross Motor Area', 'Dedicated Nap Sanctuary', 'Organic Kitchen', 'High-Res Air Purifiers'],
    imageUrl: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'prov-2',
    name: 'Sunny Sprouts Family Care',
    rating: 4.8,
    reviewCount: 34,
    distanceKm: 3.2,
    address: '88 Oakridge Boulevard',
    city: 'Richmond Hill',
    region: 'Ontario, Canada',
    isAccepting: true,
    minAgeMonths: 12,
    maxAgeYears: 6,
    hours: '8:00 AM – 6:00 PM',
    hourlyRate: 15.0,
    monthlyRate: 1180,
    licensedStatus: 'Licensed Home Child Care',
    mealsIncluded: true,
    outdoorPlay: true,
    petFree: false,
    languages: ['English', 'Mandarin'],
    capacityTotal: 8,
    capacityCurrent: 6,
    tagline: 'Nature-Inspired Exploratory Childcare & Dual-Language Learning',
    about: 'A holistic child-centered environment fostering curiosity, motor skill coordination, bilingual storytelling, and creative art exploration.',
    facilities: ['Botanical Garden', 'Natural Light Studio', 'Wooden Play Center', 'Security Gated Entry'],
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'prov-3',
    name: 'Oak Tree Child Care Sanctuary',
    rating: 5.0,
    reviewCount: 19,
    distanceKm: 4.5,
    address: '520 Highview Terrace',
    city: 'Oakville',
    region: 'Ontario, Canada',
    isAccepting: false,
    minAgeMonths: 3,
    maxAgeYears: 4,
    hours: '7:30 AM – 5:00 PM',
    hourlyRate: 18.0,
    monthlyRate: 1380,
    licensedStatus: 'Licensed Home Child Care',
    mealsIncluded: true,
    outdoorPlay: true,
    petFree: true,
    languages: ['English', 'Spanish'],
    capacityTotal: 6,
    capacityCurrent: 6,
    tagline: 'Infant & Toddler Specialized Certified Home Care',
    about: 'Intimate, low-ratio sanctuary focusing exclusively on infants and toddlers with certified pedagogical staff and hypoallergenic environment.',
    facilities: ['Infant Sensory Lounge', 'Acoustic Soundproofing', 'Hospital-Grade Sterilization', 'Organic Puree Kitchen'],
    imageUrl: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=600&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_SAFETY_TASKS: SafetyTask[] = [
  {
    id: 'task-1',
    area: 'Playroom Central Walkway',
    observation: 'Wooden toy blocks detected partially obstructing central walkway between table and safety gate.',
    priority: 'Medium',
    assignedTo: 'Clara Oswald (Lead Provider)',
    status: 'Open',
    createdAt: '09:10 AM',
  },
  {
    id: 'task-2',
    area: 'Snack & Dining Table',
    observation: 'Beverage bottle cap requires inspection to ensure tight seal and prevent floor spills.',
    priority: 'Low',
    assignedTo: 'Clara Oswald (Lead Provider)',
    status: 'In Review',
    createdAt: '11:25 AM',
  },
  {
    id: 'task-3',
    area: 'Outdoor Gate Latches',
    observation: 'Perimeter fence safety gate dual-latch verified locked prior to morning yard recess.',
    priority: 'High',
    assignedTo: 'Assistant Caregiver',
    status: 'Resolved',
    createdAt: '09:45 AM',
    resolvedAt: '09:50 AM',
  },
];

export const INITIAL_INCIDENTS: any[] = [
  {
    id: 'inc-1',
    date: '2026-09-03',
    time: '10:42 AM',
    location: 'Outdoor Soft Turf Yard',
    childId: 'child-2',
    childName: 'Liam Johnson',
    category: 'Injury',
    description: 'Minor superficial scrape on right knee after tripping over own shoelace during outdoor tag game.',
    bodyLocation: 'Right Knee',
    firstAidAdministered: 'Cleaned with sterile saline wipe, applied cold compress and dinosaur bandage.',
    immediateAction: 'Cleaned with sterile saline wipe, applied cold compress for 2 minutes, and dressed with child dinosaur bandage. Liam resumed play cheerfully within 3 minutes.',
    witnesses: 'Clara Oswald, Assistant Caregiver Marcus V.',
    staffSignatures: ['Clara Oswald, RECE', 'Marcus V.'],
    parentNotificationTime: '10:48 AM via automated secure SMS and parent portal alert',
    followUpRequired: false,
    status: 'Resolved',
  },
  {
    id: 'inc-2',
    date: '2026-08-28',
    time: '02:15 PM',
    location: 'Nap Sanctuary',
    childId: 'child-3',
    childName: 'Sophia Martinez',
    category: 'Illness',
    description: 'Mild elevated forehead warmth noted after waking from afternoon nap (measured 37.8°C / 100°F).',
    bodyLocation: 'Forehead / Temperature Elevation',
    firstAidAdministered: 'Hydration and quiet rest in comforting observation area.',
    immediateAction: 'Offered cold water, resting comfortably in quiet reading nook. Parent contacted for early pickup as per fever policy.',
    witnesses: 'Clara Oswald',
    staffSignatures: ['Clara Oswald, RECE'],
    parentNotificationTime: '02:22 PM',
    followUpRequired: true,
    status: 'Resolved',
  },
];

export const INITIAL_MEDIA_ITEMS: MediaItem[] = [
  {
    id: 'med-1',
    title: 'Morning Sensory Water & Leaves Activity',
    category: 'Outdoor play',
    childIds: ['child-1', 'child-2', 'child-6'],
    date: '2026-09-04',
    time: '10:15 AM',
    provider: 'Clara Oswald',
    consentStatus: 'Consent on File',
    visibilityStatus: 'Parent-visible',
    url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'med-2',
    title: 'Autumn Finger Painting Gallery',
    category: 'Arts & crafts',
    childIds: ['child-1', 'child-5'],
    date: '2026-09-04',
    time: '03:30 PM',
    provider: 'Clara Oswald',
    consentStatus: 'Consent on File',
    visibilityStatus: 'Parent-visible',
    url: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'med-3',
    title: 'Montessori Wooden Block Structure Engineering',
    category: 'Activities',
    childIds: ['child-4', 'child-6'],
    date: '2026-09-04',
    time: '11:45 AM',
    provider: 'Clara Oswald',
    consentStatus: 'Consent on File',
    visibilityStatus: 'Parent-visible',
    url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'audit-001',
    timestamp: '2026-09-04 08:02:14 UTC',
    actor: 'clara.oswald@daycare.provider',
    role: 'PROVIDER',
    action: 'BIOMETRIC_CHECKIN_VERIFY',
    resource: 'children/child-1/attendance',
    ipAddress: '192.168.1.104 (Hardware Edge Tablet)',
    status: 'SUCCESS',
    details: 'Biometric Face ID token verified against authorized guardian payload (Sarah Watson). Encrypted record saved.',
    sha256Hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  },
  {
    id: 'audit-002',
    timestamp: '2026-09-04 08:35:40 UTC',
    actor: 'system.security_monitor',
    role: 'AUTOMATED_MONITOR',
    action: 'AES_256_KEY_DERIVATION_AUDIT',
    resource: 'vault/medical_records/encryption',
    ipAddress: 'internal-k8s-pod-crypto-01',
    status: 'SUCCESS',
    details: 'Verified PBKDF2 100,000 iterations key derivation integrity with SHA-256 HMAC for child health records.',
    sha256Hash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
  },
  {
    id: 'audit-003',
    timestamp: '2026-09-04 09:12:05 UTC',
    actor: 'clara.oswald@daycare.provider',
    role: 'PROVIDER',
    action: 'COMPUTER_VISION_INFERENCE',
    resource: 'cv/stream/playroom_area_01',
    ipAddress: '192.168.1.104',
    status: 'SUCCESS',
    details: 'CV analysis completed (Analysis ID: VA-98A1B2C). 9 objects detected. Walkway obstruction observation flagged.',
    sha256Hash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
  },
  {
    id: 'audit-004',
    timestamp: '2026-09-04 09:20:18 UTC',
    actor: 'unauthorized.scanner.bot',
    role: 'ANONYMOUS',
    action: 'RESTRICTED_ENDPOINT_PROBE',
    resource: '/api/internal/child-pii-dump',
    ipAddress: '198.51.100.42 (Untrusted External)',
    status: 'DENIED',
    details: 'Zero Trust gateway blocked unauthorized access attempt. Rate limit and IP geofence active. Incident logged.',
    sha256Hash: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
  },
];

export interface LicensingRegionRule {
  regionCode: string;
  country: 'Canada' | 'USA';
  name: string;
  maxHomeCapacity: number;
  infantLimit: number;
  staffChildRatio: string;
  licensingBody: string;
  manualTitle: string;
  keyRequirements: string[];
}

export const LICENSING_REGIONS: LicensingRegionRule[] = [
  {
    regionCode: 'CA_ON',
    country: 'Canada',
    name: 'Ontario',
    maxHomeCapacity: 6,
    infantLimit: 3,
    staffChildRatio: '1:6 (Maximum 3 children under 2 years old)',
    licensingBody: 'Ministry of Education (Child Care and Early Years Act, 2014)',
    manualTitle: 'Home Child Care Licensing Manual (Ontario Ministry of Education)',
    keyRequirements: [
      'Maximum 6 children in home child care including provider’s own children under 4 years old.',
      'No more than 3 children younger than 2 years of age.',
      'Criminal reference check including vulnerable sector screen required for all persons age 18+ in home.',
      'Standard First Aid & Infant/Child CPR Level C certification mandatory.',
      'Written sanitary and food handling practices, daily outdoor play record, and medication logs.',
    ],
  },
  {
    regionCode: 'CA_BC',
    country: 'Canada',
    name: 'British Columbia',
    maxHomeCapacity: 7,
    infantLimit: 3,
    staffChildRatio: '1:7 (Registered Licensed Family Child Care)',
    licensingBody: 'BC Ministry of Health / Community Care and Assisted Living Act',
    manualTitle: 'Director of Licensing Standards of Practice: Family Child Care (BC)',
    keyRequirements: [
      'Maximum 7 children; no more than 3 under 36 months, and no more than 1 under 12 months.',
      '20-second handwashing protocols and secure perimeter fence of minimum 1.2m height.',
      'Current medical clearance and emergency disaster evacuation plan posted.',
    ],
  },
  {
    regionCode: 'CA_AB',
    country: 'Canada',
    name: 'Alberta',
    maxHomeCapacity: 6,
    infantLimit: 3,
    staffChildRatio: '1:6 (Licensed Family Day Home)',
    licensingBody: 'Alberta Children and Family Services',
    manualTitle: 'Family Day Home Standards Manual (Alberta Gov)',
    keyRequirements: [
      'Maximum 6 children age 0-12 including provider’s own children under age 4.',
      'Maximum 3 children under 3 years old, maximum 2 under 2 years old.',
      'Smoke detectors on every floor tested monthly with logged battery checks.',
    ],
  },
  {
    regionCode: 'US_CA',
    country: 'USA',
    name: 'California',
    maxHomeCapacity: 8,
    infantLimit: 2,
    staffChildRatio: '1:6 (Small Family Child Care Home) or 1:8 with age distribution',
    licensingBody: 'California Department of Social Services (Community Care Licensing Division)',
    manualTitle: 'Title 22 Regulations - Family Child Care Homes (California CCLD)',
    keyRequirements: [
      'Small Family Home: Up to 6 children (no more than 3 infants), or up to 8 if at least 2 are age 6+ and max 2 infants.',
      'Live Scan fingerprinting and Child Abuse Central Index (CACI) clearance.',
      'TB clearance and 16 hours of preventive health and safety training including pediatric CPR.',
    ],
  },
  {
    regionCode: 'US_NY',
    country: 'USA',
    name: 'New York',
    maxHomeCapacity: 8,
    infantLimit: 2,
    staffChildRatio: '1:6 (Family Day Care) + 2 school-age children',
    licensingBody: 'New York State Office of Children and Family Services (OCFS)',
    manualTitle: 'NYS Child Day Care Regulations Part 417 - Family Day Care Homes',
    keyRequirements: [
      'Maximum 6 children ages 6 weeks to 12 years (max 2 under 2 years), plus up to 2 school-age children.',
      'Lead testing for drinking water fixtures required every 3 years.',
      'Comprehensive Background Check (CBC) including FBI fingerprinting.',
    ],
  },
  {
    regionCode: 'US_TX',
    country: 'USA',
    name: 'Texas',
    maxHomeCapacity: 12,
    infantLimit: 4,
    staffChildRatio: '1:8 or 1:12 depending on Registered vs Licensed status',
    licensingBody: 'Texas Health and Human Services Commission (Child Care Regulation)',
    manualTitle: 'Minimum Standards for Licensed and Registered Child-Care Homes (Texas HHSC)',
    keyRequirements: [
      'Registered Child-Care Home: Up to 12 children, with age limitations (max 4 infants under 18 months).',
      'Minimum 30 hours of annual training for primary caregiver.',
      'Safe sleep crib environment with zero bumper pads, pillows, or loose blankets for infants.',
    ],
  },
  {
    regionCode: 'US_FL',
    country: 'USA',
    name: 'Florida',
    maxHomeCapacity: 10,
    infantLimit: 4,
    staffChildRatio: '1:4 (Infants) or 1:10 (Mixed age with maximum limits)',
    licensingBody: 'Florida Department of Children and Families (DCF)',
    manualTitle: 'Family Day Care Home and Large Family Child Care Home Handbook (Florida DCF)',
    keyRequirements: [
      'Family Day Care Home: Maximum 4 children from birth to 12 months, or 6 children from birth to 24 months.',
      'Mandatory 30-clock-hour Family Child Care Home training.',
      'Annual licensing inspection and radon testing if ground-floor or basement occupied.',
    ],
  },
];

export const INITIAL_DAILY_REPORTS: DailyReport[] = [
  {
    id: 'rep-1',
    childId: 'child-1',
    childName: 'Emma Watson',
    date: '2026-09-04',
    mood: 'Joyful',
    attendance: {
      checkedIn: '08:02 AM',
      checkedOut: undefined,
    },
    meals: [
      { type: 'Breakfast', eaten: 'All', items: 'Oatmeal & banana bowl finished with joy' },
      { type: 'Morning Snack', eaten: 'All', items: 'Organic apple slices & cheese' },
      { type: 'Lunch', eaten: 'All', items: 'Turkey meatballs, steamed broccoli, water' },
      { type: 'Afternoon Snack', eaten: 'Most', items: 'Yogurt smoothie & blueberries' },
    ],
    naps: [{ start: '01:05 PM', end: '02:30 PM', duration: '1h 25m', quality: 'Restful' }],
    nap: {
      started: '01:05 PM',
      ended: '02:30 PM',
      quality: 'Restful',
    },
    diapers: [{ time: '10:30 AM', type: 'Dry / Routine', notes: 'Potty routine practiced with handwashing' }],
    activities: [
      'Montessori sensory texture bin',
      'Outdoor sandcastle building & tricycle relay',
      'Finger painting autumn leaves',
      'Circle time rhyme recitation',
    ],
    providerNotes: 'Emma had an exceptional day! She enthusiastically helped Lucas pick up sensory blocks after outdoor play. No allergy symptoms observed.',
    notesForParents: 'Emma had an exceptional day! She enthusiastically helped Lucas pick up sensory blocks after outdoor play. No allergy symptoms observed.',
    parentAcknowledged: true,
    acknowledgedAt: '03:45 PM',
  },
  {
    id: 'rep-2',
    childId: 'child-2',
    childName: 'Liam Johnson',
    date: '2026-09-04',
    mood: 'Curious',
    attendance: {
      checkedIn: '08:15 AM',
      checkedOut: undefined,
    },
    meals: [
      { type: 'Breakfast', eaten: 'All', items: 'Lactose-free milk & whole wheat toast' },
      { type: 'Morning Snack', eaten: 'All', items: 'Pear slices' },
      { type: 'Lunch', eaten: 'All', items: 'Brown rice, grilled chicken strips, peas' },
      { type: 'Afternoon Snack', eaten: 'Most', items: 'Oat crackers' },
    ],
    naps: [{ start: '01:10 PM', end: '02:40 PM', duration: '1h 30m', quality: 'Restful' }],
    nap: {
      started: '01:10 PM',
      ended: '02:40 PM',
      quality: 'Restful',
    },
    diapers: [{ time: '11:15 AM', type: 'Changed', notes: 'Diaper change completed (clean & fresh)' }],
    activities: [
      'Wooden railway train engineering',
      'Playground climbing ramp practice',
      'Water table sensory exploration',
    ],
    providerNotes: 'Liam demonstrated great focus during building time. Minor knee scrape treated promptly with cold compress; rested happily.',
    notesForParents: 'Liam demonstrated great focus during building time. Minor knee scrape treated promptly with cold compress; rested happily.',
    parentAcknowledged: false,
  },
];

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'ev-1',
    title: 'Autumn Pumpkin Patch & Farm Field Trip',
    date: '2026-09-18',
    time: '09:30 AM – 01:30 PM',
    category: 'Field trip',
    description: 'Annual licensed autumn excursion to High Park botanical orchard. Signed parental permission slips required by Sept 12.',
    location: 'High Park Nature Farm',
    mandatoryAttendance: false,
  },
  {
    id: 'ev-2',
    title: 'Ontario Ministry Unannounced Licensing Audit Window',
    date: '2026-09-22',
    time: '08:00 AM – 04:00 PM',
    category: 'Inspection',
    description: 'Ministry of Education annual compliance inspection. All ratio binders, water test certificates, and daily logs ready.',
    mandatoryAttendance: true,
  },
  {
    id: 'ev-3',
    title: 'Quarterly Evacuation & Smoke Alarm Fire Drill',
    date: '2026-09-11',
    time: '10:15 AM – 10:45 AM',
    category: 'Fire drill',
    description: 'Scheduled practice for infant evacuation crib and primary gate assembly point. Timed and recorded in safety register.',
    mandatoryAttendance: true,
  },
  {
    id: 'ev-4',
    title: 'Parent-Caregiver Developmental Review Night',
    date: '2026-09-25',
    time: '06:00 PM – 07:30 PM',
    category: 'Parent conference',
    description: 'One-on-one 15-minute consultations to review developmental milestones, speech progression, and portfolio photos.',
    mandatoryAttendance: false,
  },
];

export const INITIAL_PHOTOS: PhotoItem[] = [
  {
    id: 'pho-1',
    title: 'Autumn Sensory Leaf Sorting Activity',
    caption: 'Emma and Liam identifying leaf colors and textures in outdoor yard.',
    date: '2026-09-04',
    url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop&q=80',
    childTag: 'Emma Watson, Liam Johnson',
    taggedChildren: ['Emma Watson', 'Liam Johnson'],
    coppaConsentVerified: true,
    blurSensitiveFace: false,
  },
  {
    id: 'pho-2',
    title: 'Montessori Finger Painting Masterpiece',
    caption: 'Exploring washable primary colors on textured recycled parchment.',
    date: '2026-09-04',
    url: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=800&auto=format&fit=crop&q=80',
    childTag: 'Emma Watson',
    taggedChildren: ['Emma Watson'],
    coppaConsentVerified: true,
    blurSensitiveFace: false,
  },
  {
    id: 'pho-3',
    title: 'Wooden Architecture & Balance Building',
    caption: 'Collaborative tower construction testing balance and spatial awareness.',
    date: '2026-09-03',
    url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    childTag: 'Noah Brown, Lucas Taylor',
    taggedChildren: ['Noah Brown', 'Lucas Taylor'],
    coppaConsentVerified: true,
    blurSensitiveFace: false,
  },
];

